project:
  type: website
  output-dir: docs

website:
  title: "greggj2016.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: custom_theme.scss
    css: styles.css
    toc: true



